language: node_js

node_js:
  - 10
  - 12
  # - node # runs tests against latest version of Node.js for future-proofing

before_install:
  - echo 'Installing example dependencies...'
  - npm run install-example-dependencies
  - echo 'Example dependencies installed!'

# NOTE: forcing Travis to use `npm install` instead of `npm ci`
# which was removing our examples' node_modules
install:
  - npm install

jobs:
  include:
    - stage: test
      script:
        - pwd
        - npm test
    - stage: lint
      script:
        - npm run lint
    - stage: deploy
      script: skip
      node_js: 12 # semantic-release requires Node >= 10.18
      # NOTE: Pull Request builds do not run deploy
      deploy:
        provider: script
        on:
          branch: master
        skip_cleanup: true
        script:
          - npm run release

cache:
  directories:
    - node_modules
    - examples/basic-starter/node_modules

notifications:
  email:
    on_failure: change